### ISSUE TITLE
Error creating bean with name 'mdbProps'

### ISSUE THREAD

**Issue by jsyzthz** [ykameshrao/spring-hibernate-springdata-springmvc-maven-project-framework#1]
When I change the project deployed in tomcat, start tomcat the prompt I can not find the configuration file of the "\config\props\mongodb.properties".I guess that is the "file: # {systemProperties [ 'conf.path'] }"a problem.

**Comment by ykameshrao** [comment]
Startup VM Options Required
-Dconf.path="path-to-config-folder-on-target-machine-containing-property-files"

https://github.com/ykameshrao/spring-hibernate-springdata-springmvc-maven-project-framework/wiki/Spring,-Hibernate,-Spring-Data,-Akka,-Twitter-Bootstrap,-Apache-Tiles,-jQuery-powered-Maven-Java-Web-Project-Kickstarter-Codebase

**Comment by jsyzthz** [comment]
thanks!
