### ISSUE TITLE
Registration page - button cancel throws 404 error.

### ISSUE THREAD

**Issue by cttox** [ykameshrao/spring-hibernate-springdata-springmvc-maven-project-framework#2]
Registration page - button cancel throws 404 error.

in NetBeans "WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/home] in DispatcherServlet with name 'yourWebProjectWebAppDispatcherServlet'"

**Comment by ykameshrao** [comment]
Prepend the following text to Cancel button URL in your page. 

${pageContext.request.contextPath}

**Comment by cttox** [comment]
Thanks, Kamesh.

Have a nice day.

2012/10/5 Y Kamesh Rao notifications@github.com
