### ISSUE TITLE
Jetty:run issue

### ISSUE THREAD

**Issue by johngouf** [ykameshrao/spring-hibernate-springdata-springmvc-maven-project-framework#3]
Hey there!

first of all, great work and great selection of stack.
I do have one problem thought. Not quite sure if it is just me. I was hoping you could help me out.
I issue mvn clean install and all the projects are successfully built.
When I run:
mvn jetty:run inside yourwebproject folder I get:

java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider com.sun.faces.config.FacesInitializer could not be instantiated: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/faces/webapp/FacesServlet
java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider com.sun.faces.config.FacesInitializer could not be instantiated: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/faces/webapp/FacesServlet

Am I doing something wrong?

Cheers!

**Comment by sirghost** [comment]
I think you need in your pom.xml:
[dependency]
    [groupId]javax[/groupId]
    [artifactId]javaee-web-api[/artifactId]
    [version]6.0[/version]
[/dependency]

**Comment by johngouf** [comment]
Sweet! Thanks a lot @sirghost !!
Maybe it should be added by default in the pom.xml file?
Cheers!
