### ISSUE TITLE
set -Dconf.path=”path-to-config-folder-on-target-machine-containing-property-files”

### ISSUE THREAD

**Issue by thysmichels** [ykameshrao/spring-hibernate-springdata-springmvc-maven-project-framework#4]
How do I set the following command on a Mac and what exactly must the path be?

**Comment by pablo-ungaro** [comment]
Sorry, I never use Mac, always Ubuntu.

**Comment by ykameshrao** [comment]
try this: $ export JAVA_OPTS = " -Dconf.path=path-to-config-folder-on-target-machine-containing-property-files $JAVA_OPTS"

**Comment by thysmichels** [comment]
That command did not worked I specified the path explicitly:
util:properties id="dbProps" location="file:/Users/tmichels/git/spring-hibernate-springdata-springmvc-maven-project-framework/yourwebproject/config/props/database.properties" 

Now I get this error:
ERROR [main] c.y.y.a.d.YourWebProjectApiDispatcherServlet [FrameworkServlet.java:457] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [config/spring/applicationContext-jdbc.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 0): Field or property 'dbProps' cannot be found on object of type 'org.springframework.beans.factory.config.BeanExpressionContext'

I looked in the database and the user table has been created. Any reason why it failed to found dbProps?

**Comment by thysmichels** [comment]
Failed to execute goal org.codehaus.mojo:tomcat-maven-plugin:1.1:redeploy (default-cli) on project yourwebproject: Cannot invoke Tomcat manager: Server returned HTTP response code: 403 for URL: http://127.0.0.1:8080/manager/deploy?path=%2Fyourwebproject&war=&update=true -

In which pom.xml must I add tomcat details?

**Comment by thysmichels** [comment]
I solved the issue above: my tomcat settings, deployed the war successfully. Now I get the message in Tomcat:
FAIL - Application at context path /yourwebproject could not be started

Where do I change the content path?yourwebproject.properties?
